export const ADD_INGREDIENT = 'ADD_INGREDIDENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIDENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PERCHASE_BURGER_SUCCESS = 'PERCHASE_BURGER_SUCCESS';
export const PERCHASE_BURGER_FAIL = 'PERCHASE_BURGER_FAIL';
export const PERCHASE_BURGER_START = 'PERCHASE_BURGER_START';
