export const ADD_INGREDIENT = 'ADD_INGREDIDENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIDENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

<<<<<<< HEAD
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_INIT='PURCHASE_INIT';

export const FETCH_ORDERS_START =  'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL='FETCH_ORDERS_FAIL';

=======
export const PERCHASE_BURGER_SUCCESS = 'PERCHASE_BURGER_SUCCESS';
export const PERCHASE_BURGER_FAIL = 'PERCHASE_BURGER_FAIL';
export const PERCHASE_BURGER_START = 'PERCHASE_BURGER_START';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
>>>>>>> f05df244d9fa806f0a5061e76a69ce068929f3e4
